### ISSUE TITLE
Selected Queries not working?

### ISSUE THREAD

**Issue by tailai** [chenryn/kibana-authorization#12]
Edit a panel -> Queries -> Choose 'selected' in Queries -> Click the query I want -> Choose any one in the dropdown list -> Save but query is not applied.

**Comment by chenryn** [comment]
That's maybe because the threshold I added int queries~~ The first click didn't really selected, it's in the threshold select options, you need double click -- See careful if the query has a "selected" color border.

**Comment by tailai** [comment]
Seems I misunstood this "Selected Queries" function.

My requirement is that I have two map panels(world and china), and a terms panel that shows only chinese cities. So I add a query for country_code2 field and want it works only for this terms panel. But it doesn't work when I deactivate it even I choose it in "Selected Queries". Is there a way meet my requirement in this version?

I think you could close this issue since it's nothing to do with your dropdown list.

**Comment by chenryn** [comment]
so, you want to show termfacet of two different fields in one panel? By now, you can't. Maybe you can write your own multifieldterms panel just like the multifieldhistogram panel in this version.

**Comment by tailai** [comment]
![2015-01-19 7 39 24](https://cloud.githubusercontent.com/assets/1317624/5799914/f522133c-a012-11e4-8a9c-ea08a2708837.png)

Here's my screenshot, I want the third Provinces panel to show only Chinese cities, so I'd like to apply a country code query or filter to only this panel. Thanks for your kindly help.

**Comment by chenryn** [comment]
Seems it's the just select query place. Add a `country_code2:"CN"` query and pick it in the provinces panel setting, that's ALL!
What is your "deactivate it" mean?

**Comment by tailai** [comment]
Because an acitive query will apply to ALL panels, I do not want that happen, so I "Deactivate" it

![image](https://cloud.githubusercontent.com/assets/1317624/5811332/1b1a34fc-a090-11e4-8876-48d989dc46bd.png)

But it does not apply to my "Provinces" panle any more after I deactivate this query even I choose it in "Selected Queries".

**Comment by chenryn** [comment]
so you should select other queries in other panels' setting but not deactive the query.

**Comment by tailai** [comment]
Yep, I think so. But I still think my requirement might be an enhancement, thanks for your help.

**Comment by chenryn** [comment]
yes, and I think that's why es develop the kibana4. Query no longer belongs to dashboard but to aggs/visualize.
